# Generated by Django 5.1.2 on 2024-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shawarma_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название шаурмы')),
                ('shawarma_ingredients', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ингридиенты шаурмы')),
                ('shawarma_price', models.FloatField(blank=True, null=True, verbose_name='Ингридиенты шаурмы')),
            ],
        ),
    ]
