# Generated by Django 5.1.2 on 2024-11-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ingredients_shawarma_points_shawarmas_workers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название напитка')),
                ('drink_price', models.FloatField(blank=True, null=True, verbose_name='Цена напитка')),
                ('drink_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание напитка')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название снека')),
                ('snack_price', models.FloatField(blank=True, null=True, verbose_name='Цена снека')),
                ('snack_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание снека')),
            ],
            options={
                'verbose_name': 'Снек',
                'verbose_name_plural': 'Снеки',
            },
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient_point_id',
        ),
        migrations.RemoveField(
            model_name='shawarmas',
            name='shawarma_ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.shawarmas', verbose_name='Ингредиент принадлежит к шаурме'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shawarmas',
            name='shawarma_photo',
            field=models.ImageField(null=True, upload_to='shawarmas/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес ингредиента (в граммах)'),
        ),
        migrations.AlterField(
            model_name='shawarma_points',
            name='point_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес ресторана'),
        ),
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название комбо-набора')),
                ('combo_price', models.FloatField(blank=True, null=True, verbose_name='Цена комбо-набора')),
                ('combo_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shawarmas', verbose_name='Блюдо в наборе')),
                ('combo_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drinks', verbose_name='Напиток в наборе')),
                ('combo_snacks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.snacks', verbose_name='Снек в наборе')),
            ],
            options={
                'verbose_name': 'Комбо',
                'verbose_name_plural': 'Комбо',
            },
        ),
    ]
