# Generated by Django 5.1.2 on 2024-11-08 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_combos_combo_photo_drinks_drink_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient_weight',
        ),
        migrations.CreateModel(
            name='ShawarmaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес ингредиента (в граммах)')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shawarma_ingredients', to='main.shawarmas', verbose_name='Используется в шаурме')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_shawarmas', to='main.ingredients', verbose_name='Название ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент для шаурмы',
                'verbose_name_plural': 'Ингредиенты для шаурмы',
            },
        ),
    ]
