# Generated by Django 5.1.2 on 2024-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ingredients_belongs_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='drink_carbohydrates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='drink_fats',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='drink_proteins',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='shawarmas',
            name='shawarma_carbohydrates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='shawarmas',
            name='shawarma_fats',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='shawarmas',
            name='shawarma_proteins',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='snacks',
            name='snack_carbohydrates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='snacks',
            name='snack_fats',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='snacks',
            name='snack_proteins',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Белки'),
        ),
    ]
