# Generated by Django 5.1.2 on 2024-11-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_drinks_drink_carbohydrates_drinks_drink_fats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='drink_calories',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='shawarmas',
            name='shawarma_calories',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='snacks',
            name='snack_calories',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Калории'),
        ),
    ]
